name = "ComputationAwareKalman"
uuid = "28881c16-bf71-4ba7-a6ec-419960c0da53"
authors = ["Marvin Pförtner <marvin.pfoertner@uni-tuebingen.de>"]
version = "0.1.0"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Kronecker = "2c470bb0-bcc8-11e8-3dad-c9649493f05e"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[weakdeps]
CovarianceFunctions = "b3329135-7958-41d4-bb02-e084c5a526bf"

[extensions]
ComputationAwareKalmanCovarianceFunctionsExt = ["CovarianceFunctions"]

[compat]
julia = "1"
